preset-io/backend-sdk

- src/preset_cli/cli/superset/sync/dbt/databases.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/databases_test.py
- tests/cli/superset/sync/dbt/lib_test.py
This allows us to load dbt profiles that use `env_var` for secrets.
> feat: add env_var to profiles loading

- src/preset_cli/cli/superset/sync/dbt/databases.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
We were loading the dbt profile incorrectly by first apply the Jinja2 templating then loading the YAML. But the dbt profile is valid YAML with Jinja2 as values, so the order must be reversed — first load the YAML, then apply Jinja2 to the leaves.
I also implemented a few filters that dbt provides:
- `as_bool`
- `as_number`
- `as_native`
- `as_text`
As well as adding `project_name` and `target` to the template context.
> fix: dbt profile loading

- src/preset_cli/cli/superset/sync/dbt/datasets.py
Allow passing arbitrary metadata to datasets from models:
```yaml
models:
- name: customers
description: One record per customer
meta:
superset:
cache_timeout: 600
columns:
- name: customer_id
description: Primary key
tests:
- unique
- not_null
- name: first_order_date
description: NULL when a customer has not yet placed an order.
```
> feat: allow passing dataset metadata

- src/preset_cli/cli/main.py
- tests/cli/main_test.py
Allow running `preset-cli auth --overwrite` when the credentials exist and have been expired.
> fix: renew expired creds

- README.rst
- src/preset_cli/cli/superset/export.py
- tests/cli/superset/export_test.py
When running `preset-cli superset export` this will escape any existing JInja2 in dataset definitions, so that the assets cab imported back with `preset-cli superset sync native`.
> fix: escape Jinja in exported assets

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/lib_test.py
Allow using the [node selection syntax(https://docs.getdbt.com/reference/node-selection/syntax) to choose which models should be synced.
Currently supports tags, plus, n-plus, and at operators.
> feat: dbt selectors for sync

- README.rst
- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/export.py
- src/preset_cli/cli/superset/main.py
- tests/api/clients/superset_test.py
- tests/cli/superset/export_test.py
- tests/cli/superset/main_test.py
Create a mapping between resource (dataset, chart, dashboard) UUID and owner emails:
```bash
$ superset-cli -u admin -p admin http://localhost:8088/ export-ownership
$ cat ownership.yaml
dataset:
- name: test_table
owners:
- admin@dealmeida.net
uuid: e4e6a14b-c3e8-4fdf-a850-183ba6ce15e0
```
> feat: export ownership

- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/import_.py
- src/preset_cli/cli/superset/main.py
- tests/api/clients/superset_test.py
- tests/cli/superset/import_test.py
- tests/cli/superset/main_test.py
Allow updating ownership of resources (datasets, charts, dashboards) based on an export from https://github.com/preset-io/backend-sdk/pull/58.
> feat: import ownership information

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
When exporting roles, include also the users (identified by email) that belong to each role, so it can be reimported.
> feat: export roles with users

- src/preset_cli/cli/superset/main.py
- tests/cli/superset/main_test.py
Allow passing a JWT to Superset:
```bash
$ superset-cli --jwt-token=XXX http://localhost:8088/ export
```
> feat: allow passing a JWT to superset

- src/preset_cli/api/clients/preset.py
- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/main.py
- tests/api/clients/preset_test.py
- tests/api/clients/superset_test.py
This sets explicit logging for API requests.
Alternatively we could set the debug level in the `urllib3` library directly (see https://requests.readthedocs.io/en/latest/api/?highlight=logging#api-changes), but I tried and it's too verbose.
> chore: add debug logging to all API requests

- src/preset_cli/cli/superset/export.py
- tests/cli/superset/export_test.py
- tests/cli/superset/main_test.py
```bash
$ superset-cli http://localhost:8088/ export ~/export --asset-type=dashboard --asset-type=chart
```
Will export only charts and dashboards.
> feat: allow specifying asset types

- src/preset_cli/cli/main.py
- src/preset_cli/cli/superset/export.py
- src/preset_cli/cli/superset/main.py
- src/preset_cli/lib.py
- tests/api/clients/preset_test.py
- tests/cli/main_test.py
- tests/cli/superset/export_test.py
- tests/cli/superset/main_test.py
Allow specifying resource ID when exporting. Eg:
```bash
$ superset-cli http://localhost:8088/ export --asset-type=dashboard --dashboard-ids=1,2,3
```
Will only export dashboards with IDs 1, 2, and 3.
> feat: export resources by ID

- src/preset_cli/cli/superset/export.py
- tests/cli/superset/export_test.py
This PR introduces a few changes to the `superset export` command. First, if IDs are specified for any resource type, then all assets are exported by ID. The command:
```bash
superset-cli export --database-ids=1,2
```
Will export only databases with ID 1 and 2, and no datasets, charts, nor dashboards will be exported. **Before:** this would export databases with ID 1 and 2, but also **all** datasets, charts, and dashboards.
Second, when an ID is specified, related assets are also exported. The command:
```bash
superset-cli export --dashboard-ids=1 --asset-type=dashboard
```
Will export dashboard with ID 1, but also all its associated charts, datasets, and databases. **Before:** this would export only the dashboard with ID 1, but not export associated resources.
IDs for multiple resource …
> chore: improve export by ID

- src/preset_cli/api/clients/preset.py
- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/main.py
- tests/api/clients/preset_test.py
- tests/api/clients/superset_test.py
- tests/cli/main_test.py
Given a YAML file `user_roles.yaml`:
```yaml
- email: ralmeida+10@gmail.com
team_role: admin 
workspaces:
Strategic Pod:
workspace_role: Limited Contributor
data_access_roles:
- test Public
```
We can sync team/workspace/DAR roles to Preset with:
```bash
$ preset-cli sync-roles
```
> feat: sync user roles

- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/api/clients/superset_test.py
- tests/cli/superset/sync/dbt/datasets_test.py
Allow syncing models that are in different (sub) databases. Closes https://github.com/preset-io/backend-sdk/issues/73.
For example, the SQL Alchemy for a given database might be `bigquery://project_A`, but the user might want to add a model that is defined in `project_B`. Since Superset doesn't allow creating a physical dataset in cases like this, we create a simple virtual dataset defined by:
```sql
SELECT * FROM project_B.schema.table;
```
> feat: support datasets in other (sub) DBs

- src/preset_cli/cli/main.py
- tests/cli/main_test.py
> feat: allow reading workspaces from the environment

- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
The ``exclude`` option for dbt nodes was failing when a node was referenced twice; the second exclusion would fail because the node no longer existed..
> fix: prevent node from being excluded twice

- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
Allow passing a DUO generated passcode to the [dbt config](https://docs.getdbt.com/reference/warehouse-setups/snowflake-setup#user--password--duo-mfa-authentication):
```yaml
my-snowflake-db:
target: dev
outputs:
dev:
type: snowflake
account: [account id]
user: [username]
password: [password]
authenticator: username_password_mfa  # HERE
...
"""
> feat: support DUO MFA passcode in Snowflake

- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/databases.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/databases_test.py
- tests/cli/superset/sync/dbt/lib_test.py
Allow passing `dbt_project.yml` instead of `manifest.json`, since it has more information and we can infer the manifest location from it.
> feat (dbt): pass `dbt_project.yml`

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
Tentative fix for https://github.com/preset-io/backend-sdk/issues/113.
When creating a virtual dataset from a dbt model in Snowflake we're getting the following error:
```
[[09:32:48]] ERROR: preset_cli.cli.superset.sync.dbt.datasets: Unable to create dataset                                                                                                           datasets.py:99
Traceback (most recent call last):                                                                                                                                                                              
File "/usr/local/lib/python3.9/site-packages/preset_cli/cli/superset/sync/dbt/datasets.py", line 97, in sync_datasets …
```
> fix: allow `None` as a column type

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
Before running an import with `superset sync native` test the DB connectivity and warn if it fails (failure could be expected, depending on the network configuration).
> feat: check DB connectivity before import

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
Prevent logging the database password when we can't connect to it.
cc: @cwegener
> fix: don't log password

- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
This PR introduces a few changes to the `superset sync native` command:
1. The `--asset-type` option was removed, since it was broken. When importing an asset (say, a dataset) all related assets should be included in the bundle (database, in this example), which defeats the purpose of syncing only a few assets.
2. The command now uses the `/api/v1/assets/import` endpoint in Superset, requiring a single request instead of 4 separate requests.
3. A new option `--split` was added. When set the CLI will imports assets one by one (with related assets), starting with databases, then datasets, charts, dashboards.
```bash
$ preset-cli --workspaces=https://816a0e96.us2a.app.preset.io/ superset sync native ~/Projects/headless-bi-blog-post-examples/ --overwrite --split …
```
> feat (native sync): split imports and more

- src/preset_cli/api/clients/preset.py
- src/preset_cli/api/clients/superset.py
- src/preset_cli/auth/lib.py
- src/preset_cli/cli/main.py
- tests/api/clients/preset_test.py
- tests/api/clients/superset_test.py
- tests/auth/jwt_test.py
- tests/auth/lib_test.py
- tests/cli/main_test.py
Switches manager baseUrl from `manage.app.preset.io` over to `api.app.preset.io`
> chore: Switching URL to api.app.preset.io

- src/preset_cli/cli/superset/sync/dbt/command.py
- tests/cli/superset/sync/dbt/command_test.py
If the user doesn't specify a job ID, prompt them for one progressively (account ID, project ID, job ID).
> feat (dbt cloud): prompt for account/project/job

- .flake8
- src/preset_cli/api/clients/preset.py
- src/preset_cli/cli/main.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/exposures.py
- tests/cli/main_test.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/exposures_test.py
The CLI currently offers a command to populate dbt exposures — these are charts and dashboards in Superset that were created based on datasets that map back to dbt models.
Currently, the CLI uses **extra metadata that is added to datasets** when the CLI syncs them from dbt to Superset, eg:
```json
{
"datasource_type": "table",
"schema": "public",
"table_name": "messages_channels",
...
"extra": {
"resource_type": "model",
"unique_id": "model.superset_examples.messages_channels",
"depends_on": "ref('messages_channels')"
}
}
```
This makes the process of determining which charts and dashboards read from dbt models easy, since we can just check the extra metadata.
A customer has expressed the need for populating exposures from Preset when they have created the dataset manually. Since the …
> feat: infer dbt models from dataset

- .github/workflows/python-package-daily.yml
- .github/workflows/python-package.yml
- dev-requirements.txt
- requirements.txt
- setup.cfg
Python 3.11 was released today, and our unit tests pass with it. Adding it to unit tests and metadata as a supported version.
> chore: add 3.11

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/api/clients/preset.py
- src/preset_cli/api/clients/superset.py
- src/preset_cli/auth/jwt.py
- src/preset_cli/auth/main.py
- src/preset_cli/auth/password.py
- src/preset_cli/auth/preset.py
- src/preset_cli/auth/token.py
- src/preset_cli/cli/main.py
- src/preset_cli/cli/superset/sync/dbt/exposures.py
- tests/auth/jwt_test.py
- tests/auth/main_test.py
- tests/auth/preset_test.py
- tests/cli/main_test.py
- tests/cli/superset/sync/dbt/exposures_test.py
A customer needs to run a really big import (~12 hours), but the JWT is only valid for 5. So I added some logic to refresh authentication (across all mechanisms) whenever needed.
The main auth class (simplified) now looks like this:
```python
class Auth:  # pylint: disable=too-few-public-methods
def __init__(self):
self.session = Session()
self.session.hooks["response"].append(self.reauth)
def auth(self) -> None:
raise NotImplementedError("Must be implemented for reauthorizing")
def reauth(self, r: Response, *args: Any, **kwargs: Any) -> Response:
if r.status_code != 401:
return r
try:
self.auth()
except NotImplementedError:
return r
self.session.headers.update(self.get_headers())
r.request.headers.update(self.get_headers())
return self.session.send(r.request, verify=False)
```
On …
> feat: refresh JWT whenever needed

- dev-requirements.txt
- requirements.txt
- setup.cfg
- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
A customer is running a big import, and mid-process the CLI will fail with a `ConnectionError`. I added retries to the import command trying to fix it.
> feat: retry imports on connection error

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
When running `import_resources_individually`, write progress to a file called `checkpoint.log`. If the import fails, the file is used to skipped already imported assets on the next run.
> feat (native): add checkpoint file

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
When doing an asset sync, if a database YAML file has a masked password (eg, `postgresql://user:XXXXXXXXXX@host:5432/dbname`) and the database already exists, don't prompt users for the password. We can simply pass the masked password and Superset will do the right thing.
Also fix a dataset bug I found when exporting the `examples` database. For some reason the `params` attribute in the dataset is a string:
```yaml
table_name: Video Game Sales
schema: public
sql: ''
params: '{"remote_id": 64, "database_name": "examples", "import_time": 1606677834}'
...
```
Even though it should be an object:
https://github.com/apache/superset/blob/d3f930a5575f03bc5f4f468b8bf37e834bf2aa4d/superset/datasets/commands/export.py#L61
> fix (native): no password prompt on db update

- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/exposures.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/exposures_test.py
Allow syncing only exposures from Preset workspaces to a YAML file.
This now works with both dbt Cloud and dbt Core:
```bash
$ preset-cli superset sync dbt-core ... --exposures=exposures.yaml --exposures-only
$ preset-cli superset sync dbt-cloud ... --exposures=exposures.yaml --exposures-only
```
The datasets don't have to be created via the CLI for the exposure discovery to work. The command will look at all models (filtered by `--select` and `--excluded`, if set) and figure out which datasets correspond to them based on the the database, schema, and table name.
> feat (dbt): allow syncing only exposures

- src/preset_cli/cli/superset/sync/dbt/databases.py
- tests/cli/superset/sync/dbt/databases_test.py
Fixes a bug where the db lookup was keying off the project name instead of the profile name when syncing a  database. 
I changed the profile name in the tests to be different from the project so that we can double-check where the lookup is happening. 
fixes: https://github.com/preset-io/backend-sdk/issues/144
> use profile instead of project on db lookup

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
When updating columns descriptions we're not passing other metadata like `is_dttm`, which causes temporal columns to be marked as non-temporal after a sync.
I fixed it by fetching the column definitions, applying updates from dbt, and doing the column update.
Closes #152
> fix: preserve is_dttm on column update

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/command_test.py
Fixes #157 
We were dropping the new metric fields when loading the metrics. I added them to `MetricSchema`, and also changed the loading so that we don't drop new fields in the future.
> Fix `MetricSchema` loading

- src/preset_cli/api/clients/superset.py
When exporting roles from a Preset workspace (or Superset instance), ignore users which we can't find an email for (since the export is based on email).
> fix: ignore missing users in export-roles

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
For some reason the CLI is pushing `is_active=null` to the API when updating columns, something that should never happen:
```
ERROR: preset_cli.lib: {"message":{"columns":{"0":{"is_active":["Field may not be null."]},"1":{"is_active":["Field may not be null."]},"2":{"is_active":["Field may not be null."]},"3":{"is_active":["Field may not be null."]},"4":{"is_active":["Field may not be null."]},"5":{"is_active":["Field may not be null."]}}}} 
```
I changed the CLI so that when a column has `is_active` set to `None` we remove it from the update, preserving the existing value.
> fix: ensure is_active is true

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
Make `import-roles` update the role if it already exists.
> feat: make import-roles idempotent

- README.rst
* Moved the DB creation/link part to the dbt core section
* Added a section to highlight that the db connection must already exist on the workspace when syncing from dbt cloud, and that the display name must match the db name.
> update dbt sync section on readme

- .pre-commit-config.yaml
- src/preset_cli/cli/main.py
* Preset has recently introduced a new Workspace Role: **Secondary Contributor**. Added support for this role (`PresetBeta`).
* Also added an emoji for Workspaces in hibernated status.
> Add support for Secondary Contributor (new Workspace Role)

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
Models in dbt can have alias, eg:
```sql
-- foo.sql
{{ config (alias = 'model_alias') }}
SELECT ...
```
In this case, instead of the table created being called `foo` it will be called `model_alias`. When creating the Superset dataset pointing to the table we should use the alias in this case.
Closes https://github.com/preset-io/backend-sdk/issues/173.
> fix: use table alias when creating dataset

- src/preset_cli/api/clients/dbt.py
Add a header to the dbt client identifying us as a partner.
> chore: add X-dbt-partner-source header

- README.rst
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/databases.py
- tests/cli/superset/sync/dbt/databases_test.py
Currently, the CLI would always update the DB connection configuration on the Workspace using the information from the `profiles.yml` file (regardless if `--import-db` was passed or not). The flag was only validated in case **no database connection was found**.
This PR introduces the ability to perform a dbt sync without updating the DB connection. This is very useful in case the dbt configuration uses different credentials, or even a different authentication method that might not be supported by Superset.
> (chore) Supporting dbt sync without updating the db connection configuration on Superset

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
We were not syncing the column labels, only their descriptions.
> feat(dbt): sync column label

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/datasets_test.py
The schema for column metadata used by dbt Core is slightly different from the dbt Cloud response schema. For the former:
```json
{"columns": {"customer_id": {"name": "customer_id", "description": "some description"}}}
```
And for the latter:
```json
{"columns": [{"name": "customer_id", "description": "some description"}]}
```
Because of this, when using dbt Cloud the column metadata was not being synced. I fixed it by setting the dbt Cloud as the standard; when reading the column metadata from the manifest in dbt Core we modify the schema to match the one in dbt Cloud.
> fix(dbt): dbt Cloud columns as the standard

- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/metrics_test.py
There are two ways to represent derived metrics in dbt. Before dbt 1.3:
```yaml
- name: some_ratio
type: expression
sql: "{{metric(a)}} / {{metric(b)}}"
```
Starting with dbt 1.3:
```yaml
- name: some_ratio
calculation_method: derived
expression: "{{metric(a)}} / {{metric(b)}}
```
For some reason, the API for dbt Cloud returns a derived metric as:
```json
{
"name": "ratio_of_paying_customers",
"sql": "paying_customers / total_customers",
"type": "derived",
"unique_id": "metric.jaffle_shop.ratio_of_paying_customers",
}
```
This PR fixes the `is_derived` function to handle this correctly.
> fix: derived metrics in dbt Cloud

- src/preset_cli/cli/superset/sync/dbt/databases.py
Currently, for the dbt sync the database connection would only be created/updated in Superset in case `--import-db` was passed. However, the CLI was still building the SQLAlchemy URI regardless of this flag, which would still throw an error in case the DB authentication method in DBT is un-supported in Preset. 
With this PR, `build_sqlalchemy_params()` is only called in case `import_db == True`.
> Do not build SQLAlchemy URI in case the database won't be imported/modified

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
Allow passing a certification payload when syncing datasets from dbt.
> feat: allow passing a certification payload

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
Users now will be able to filter `Model.config` values when running the cli
```
$ dbt run --select config.materialized:view
{{ config(
materialized = 'view',
unique_key = ['column_a', 'column_b'],
grants = {'select': ['reporter', 'analysts']},
transient = true
) }}
```
> Adding config option for filtering models

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
Due to a CVE, some of the information available in `api/v1/database/$id` was moved to `api/v1/database/$id/connection`. This PR updates the Superset client to try both endpoints.
Added a test covering the case.
> fix(superset): `get_database`

- CHANGELOG.rst
- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
This PR introduces the ability to control `certification` information from the dbt models definition. Previously, the certification would be automatically set to:
``` json
{
"certification":
{
"details": "This table is produced by dbt"
}
```
Now, the `certification` can be defined on the `meta.superset.extra.certification` field. For example:
``` yaml
models:
- name: dbt_vehicle_sales
meta:
superset:
extra:
certification: 
certified_by: Data Analytics team
details: Vehicle Sales data
```
It's also possible to set `certification` to `null`, to prevent displaying the pop up in the Superset UI (useful in case the model is not ready yet for Production use):
``` yaml
models:
- name: dbt_vehicle_sales
meta:
superset:
extra:
certification: null
```
Additional fields can also be specified for the …
> feat: sync certification information from dbt models

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
This PR adds a few fixes/improvements to the dataset certification flow:
* In case the `certification` is set to `null` via the dbt model definition, before we were setting `certification: null` in the dataset, which wouldn't show the certification pop up, but it would still include the dataset when filtering for `certified: yes`. With these changes, in case `certification` is set to `null` in the model definition, the `certification` key won't be included in the dataset's `extra` field.
* Renamed the `certification` local variable to `certification_info` to better distinguish from the function argument. Also changed its content to a dictionary to only include the key pair in the `extra` definition in case it contains an actual value.
* Updated the test for the new desired flow.
> fix: Removing the certification key in case certification is null

- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/datasets.py
- src/preset_cli/cli/superset/sync/dbt/exposures.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/datasets_test.py
- tests/cli/superset/sync/dbt/exposures_test.py
This PR addresses a few issues with the exposures sync:
* In the past, we were not including the single quotes to specify the model name [here](https://github.com/preset-io/backend-sdk/blob/main/src/preset_cli/cli/superset/sync/dbt/command.py#L137), which could cause https://github.com/preset-io/backend-sdk/issues/208
* The asset titles were used as the `name` for exposures, which could contain [incompatible characters](https://docs.getdbt.com/reference/exposure-properties): https://github.com/preset-io/backend-sdk/issues/207 and https://github.com/preset-io/backend-sdk/issues/177
* Charts don't have a `query_context` value until they are viewed in Explore, which could cause: https://github.com/preset-io/backend-sdk/issues/206
This PR also introduces a new flag to the dbt sync: …
> (fix)Exposures definitions and added ability to preserve columns

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
The `get_role_id()` function was previously configured to use ``{"_flt_0_name": role_name}``. The ``0`` filter index is used for **Starts with**, so in case there are more than one DARs starting with the same name from the YAML file, multiple results would be returned.
This PR changes the filter index to ``3`` which is used for the **Equals** filter operator. The ``3`` filter operator was already being used [here](https://github.com/preset-io/backend-sdk/blob/main/src/preset_cli/api/clients/superset.py#L920), so this should be a minor change.
> (fix)get_role_id() was returning multiple results

- src/preset_cli/cli/main.py
- src/preset_cli/cli/superset/export.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/datasets.py
- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/main_test.py
- tests/cli/superset/export_test.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/databases_test.py
- tests/cli/superset/sync/dbt/datasets_test.py
- tests/cli/superset/sync/native/command_test.py
By default, when triggering a dbt sync the CLI:
1. Delete all existing metrics from the dataset.
2. Create metrics based on the dbt definitions.
While this is the expected scenario for the integration (to preserve dbt as the source of truth), this approach can be impactful for organizations that are already extensively using Preset/Superset and therefore have custom metrics defined in their datasets that don't exist in dbt yet. For these cases, the sync could result in broken charts/dashboards, since metrics that only exist in Preset don't get re-created.
This PR introduces two modifications:
* Changing the `--preserve-columns` flag to `--preserve-metadata`: The `--preserve-columns` was used to prevent a column sync during the update, to properly preserve column configs (**Is temporal**, …
> feat(dbt sync): Merge metadata and preserve Preset configs

- src/preset_cli/cli/superset/export.py
- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/export_test.py
- tests/cli/superset/sync/native/command_test.py
Since the CLI supports Jinja templating to dynamically modify the asset contents during the import, it automatically escapes existing Jinja templating syntax from assets during the export, so that they are ignored by the CLI renderer until import (and properly preserved to be handled by Superset). 
Recently the `query_context` was introduced to chart exports, which is a JSON structure converted to a string. The CLI was incorrectly escaping the JSON structure (`{"key_one: {"key_two: "value" {{ '}}' }}`) as if it was Jinja templating syntax during the export, causing the import to fail.
This PR improves the Jinja escaping logic, trying to load any string field as a JSON (the most common field is the `query_context` but we have other JSON fields that are exported as strings) so that only …
> fix(import/export): Improve Jinja handling logic

- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
This PR adds the ability to specify the models that should be synced using their relative path. Both specifying files (for example `--select models/my_model.sql`) and folders (for example `--select models/prod`) work. When selecting a folder, it supports the inclusion or not of the last trailing slash(`--select models/prod == --select models/prod/`). 
It's also possible to use `*` after the folder name, however for this approach it's required to pass the argument as a string -> `--select "models/prod/*"` otherwise the terminal automatically creates one argument per file, breaking the CLI.
Implements https://github.com/preset-io/backend-sdk/issues/217 and https://github.com/preset-io/backend-sdk/issues/171.
> chore(dbt-sync): Allow the specification of dbt models using their path

- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- tests/cli/superset/sync/dbt/command_test.py
A refactor preparing the support for dbt 1.6. For the new semantic layer we need access to the environment ID, so we need the full job information, not just the ID.
Updated tests and added new ones.
> chore(dbt cloud): return job instead of job ID

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/datasets.py
- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/api/clients/dbt_test.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/datasets_test.py
- tests/cli/superset/sync/dbt/manifest.json
- tests/cli/superset/sync/dbt/metrics_test.py
When syncing metrics in the dbt command, we currently pass the metrics as `List[MetricSchema]` to `sync_datasets`, where `MetricSchema` is the schema returned by dbt Core/Cloud. This PR refactors the logic so we pass instead the metric in the schema that Superset uses. This will simplify the work needed to support dbt 1.6, which introduces yet another format for metrics.
Note that this PR is stacked upon https://github.com/preset-io/backend-sdk/pull/253.
> chore (dbt): pass metric definition

- dev-requirements.txt
- requirements.txt
- setup.cfg
- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/exposures.py
- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/api/clients/dbt_test.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/exposures_test.py
- tests/cli/superset/sync/dbt/metrics_test.py
This PR introduces an algorithm for syncing dbt metrics defined using [MetricFlow](https://docs.getdbt.com/docs/build/sl-getting-started). In order to sync metrics it:
1. Queries a new GraphQL endpoint to get all the names of the metrics
2. Queries a new GraphQL endpoint to get the SQL for each of the metrics
3. Converts the SQL (a full query) into a projection, using an algorithm similar to the one used with older metrics
Because in MetricFlow metrics are a higher concept, not all metrics can be converted. For example, a metric could be "sales in France", having an implicit `JOIN` in them. Metrics with joins and/or multiple tables are ignored, and the error is logged.
Note that MetricFlow has a concept called "measure" which is much closer to the Superset metric. Unfortunately the …
> feat(dbt): sync metrics from MetricFlow

- src/preset_cli/cli/superset/sync/dbt/command.py
Consolidate some logic in a function, since it will have to be called by manager when syncing dbt metrics.
> chore(dbt): move logic to a function

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- tests/api/clients/dbt_test.py
Add support for passing a custom access URL for the dbt APIs. This will be needed later this year, see https://docs.google.com/document/d/1oiyACMtQaxlbp90LKIh3EyUqBnzZM5NfuTW25fWhDA0/edit.
Ticket: https://app.shortcut.com/preset/story/78260/dbt-update-ui-to-ask-for-urls
> feat(dbt): allow passing custom URL

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/metrics_test.py
[PR#254](https://github.com/preset-io/backend-sdk/pull/254/files#diff-6a9da321f6c92c5e31f999ebd04d4f2f1c0dceb066d3aae0d59cc836eb2444b4R157-R164) introduced a new pattern for mapping metrics:
``` python
metric_map = {metric["unique_id"]: metric for metric in metrics}
```
This ended up affecting our ability to parse derived metrics, given the metric macro renders the metric `name`, rather than its `unique_id`. As a consequence, [this condition](https://github.com/preset-io/backend-sdk/pull/255/files#diff-6a9da321f6c92c5e31f999ebd04d4f2f1c0dceb066d3aae0d59cc836eb2444b4R81-R82) was never met (since `token.sql()` would return the macro name):
``` python
for token in tokens:
if token.sql() in metrics:
```
This section of the code is only used by legacy dbt versions -- for new versions we're …
> fix(dbt): Support syncing derived metrics on legacy dbt versions

- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/metrics_test.py
The CLI uses `sqlglot` to parse SQL syntax from dbt metrics. While we were specifying the SQL dialect when parsing the query, we were not specifying the dialect when converting the parsed result back to SQL, which would cause issues with engine-specific syntaxes. Some examples:
* A BQ metric created using `IF()` statement would get converted to `CASE` (would still work but different syntax)
* A BQ metric created using `DATE_DIFF()` would get converted to `DATEDIFF()` which doesn't work with BQ.
> fix(sqlglot): Convert metric syntax back to dialect-specific after parsing it

- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/metrics_test.py
When creating a `COUNT (DISTINCT x)` metric with a filter -- for example:
``` yaml
semantic_models:
- name: datadiff_test
...
measures:
- name: distinct_count_test
expr: id
description: "The count of unique rows."
agg: count_distinct
dimensions:
- name: quantity
type: categorical
...
metrics:
- name: test_distinct_metric
description: "The number of unique rows."
type: simple
label: Number of CX Sent Secure Messages
type_params:
measure: distinct_count_test
filter: |                                     
{{  Dimension('id__quantity') }} > 10
```
The metric conversion would result in an incompatible syntax:
``` sql
COUNT(CASE WHEN quantity > 10 THEN DISTINCT id END)
```
This PR updates the logic to replace the `DISTINCT` as needed:
``` sql
COUNT(DISTINCT CASE WHEN quantity > 10 THEN id END) …
```
> fix(dbt): Support filtered COUNT DISTINCT in metrics

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
The response payload for ``create_dataset()`` is different than the one for ``client.get_dataset()``. This was causing an error as the actual dataset data (`metrics`, `columns`, etc) was nested under `data` for the creation command.
I could change the `return` statement to `dataset["data"]` (to avoid firing another API call) but I believe this way is easier to maintain in the long-term (otherwise we'll be exposed to issues when either of these two schema changes, and they could differ over time).
> fix(dbt): Dataset creation returns a different schema

- CHANGELOG.rst
Preparing for release `0.2.13`. 
Also fixed the `CHANGELOG` syntax that got broken after `0.2.2`:
> chore: 0.2.13 release

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/metrics_test.py
dbt allows the creation of derived metrics with just raw SQL, not involving any other dbt metric:
``` yaml
metrics:
- name: new_derived_again
label: test
calculation_method: derived
expression: |
{% raw %}
(SUM(price_each)) * 1.2
{% endraw %}
```
These would currently fail to sync, as derived metrics don't have a `model` definition, so currently the CLI identifies the desired model by getting the models used by the metrics used in the syntax (which don't exist in this case).
To support this flow, the CLI now will get the model's `unique_id` from `meta.superset.model` for such metrics:
``` yaml
metrics:
- name: new_derived_again
label: test
calculation_method: derived
expression: |
{% raw %}
(SUM(price_each)) * 1.2
{% endraw %}
meta:
superset:
model: model.postgres.vehicle_sales
```
the …
> fix(dbt-derived-metrics): Support raw metrics and Jinja syntax

- CHANGELOG.rst
- CONTRIBUTING.rst
Preparing for release `0.2.14`. Also fixed a URL syntax in the  CONTRIBUTING file.
> chore: 0.2.14 release

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
During the `sync native` command, the CLI has to identify all existing DB connections in the target instance/Workspace (and their corresponding UUIDs). This is currently achieved by exporting each DB connection, and getting the `uuid` from the YAML file. 
This process was adopted because the `uuid` is not exposed in the API response for older Superset versions. However, it affects performance for two reasons:
* Each DB connection is exported (the more connections created, the longer it would take).
* There was a change in Superset that exporting a DB connection also includes all datasets, which can take time for connections with hundreds/thousands of datasets.
This PR defaults the process to get the `uuid` from the API response, and fallback in the old approach in case the API response …
> chore(sync native): Attempt to get the DB connection UUIDs via API

- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/metrics_test.py
https://github.com/preset-io/backend-sdk/pull/277 introduced the ability to sync metrics from dbt with Jinja syntax, which could also include other metrics. For example:
``` yaml
metrics:
- name: revenue
label: test label
calculation_method: sum
expression: price_each
- name: derived_metric_with_jinja
label: test label
calculation_method: derived
expression: |
{% raw %}
SUM(
{% for x in filter_values('x_values') %}
{{ + x_values }}
{% endfor %}
)
{% endraw %}
/ {{ metric('revenue') }}
```
However, the other way around (creating a derived metric including another derived metric with Jinja) wasn't supported yet:
``` yaml
metrics:
- name: derived_metric_with_jinja
label: test label
calculation_method: derived
expression: |
{% raw %}
SUM(
{% for x in filter_values('x_values') %}
{{ + x_values …
```
> fix(derived metrics): Support reusing metrics with Jinja in other metrics

- src/preset_cli/cli/superset/sync/dbt/command.py
- tests/cli/superset/sync/dbt/command_test.py
fixes #279 
Uses `load_profiles` function so that it reads variables defined as JINJA on `profiles.yml`
> fix(dbt): Load profiles with Jinja

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/metrics_test.py
The CLI allows users to sync specific models via dbt. As a consequence, when evaluating metrics it's expected that some will rely on models that aren't included in the ``model_map``. This PR changes the logic to avoid raising a  ``ValueError`` in this scenario and instead just ignore the metric.
> fix(dbt): Avoid raising an error when syncing specific models

- setup.cfg
- src/preset_cli/cli/superset/sync/dbt/datasets.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/datasets_test.py
- tests/cli/superset/sync/dbt/lib_test.py
dbt is compatible with warehouses that support creating multiple DBs in the same instance (such as Snowflake). Since the `database` is specified in the DB connection string in Superset, when a model is created in a different database, the CLI creates it as a virtual dataset (using `select * from db_name.schema.table`). 
SQLAlchemy's `create_engine()` method might require the DB-specific driver to work. This PR adds proper instructions to users when facing this issue. It currently only covers `snowflake`, but covering more engines should be straightforward.
> chore(dbt): Instruct users of missing dependency when creating a Snowflake virtual dataset

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
Redshift reflection query returns additional metadata that isn't compatible with the Superset column schema. This PR removes the `info` key when syncing columns.
I think long-term solution is to enforce the Superset schema for columns and metrics accordingly -- I'll look into that in a future PR.
> fix(dbt): Remove Redshift-specific column metadata

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
The `sync native` / `import-assets` command allows users to include a `--split` flag to import resources individually. It's possible to create dashboard filters using datasets that aren't used by any chart. The logic was currently not including these datasets when importing the dashboard, resulting in an import error.
> fix(import-assets): Include all dashboard depedencies when using the the --split flag

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
With SIP-95 implemented we don't need virtual datasets anymore, yay!
Note: ideally this still requires testing with a real project, and also for the SIP-95 branch to be deployed at Preset.
> chore: avoid virtual datasets whenever possible

- src/preset_cli/api/clients/dbt.py
We got a report from a user that was unable to execute a dbt Cloud sync with below error:
```
marshmallow.exceptions.ValidationError: {'columns': ['Field may not be null.']}
```
This was happening because they have models returned in the API response with `columns` set to `None`. This PR changes the schema to support this scenario.
> fix(ModelSchema): Allow models with columns set to None

- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/lib.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/lib_test.py
It's possible to trigger the dbt Core sync specifying the path to either the `manifest.json` file or to the `dbt_project.yml` file. The former would currently display a `DeprecationWarning`.
[dbt deprecated the `target-path` as a config in the `dbt_project.yml`](https://docs.getdbt.com/reference/global-configs/about-global-configs) (which is used when triggering the command with this file) so this PR is moving the deprecated warning to when syncing with the path to `dbt_project.yml` file specified. For simplicity, I would recommend dropping support entirely in a future release and relying solely in the `manifest.json` file.
This PR also moves away from using `warnings.warn()` as it breaks logging (not a concern when using the `preset-cli` as a standalone CLI, but could be impactful when …
> chore(dbt sync): Deprecate using the dbt_project file to trigger a dbt sync

- src/preset_cli/api/clients/dbt.py
- tests/api/clients/dbt_test.py
If the project doesn't have a semantic layer, the query to fetch semantic layer metrics return below response:
``` json
{
"data": null,
"errors": [
{
"message": "Empty semantic manifest was found. Ensure that you have semantic models defined.",
"locations": [{"line": 3, "column": 17}],
"path": ["metrics"],
},
],
}
```
This PR adds support for this scenario.
> fix(dbt Cloud): Support syncing a project without a semantic layer

- src/preset_cli/cli/superset/sync/dbt/command.py
- tests/cli/superset/sync/dbt/command_test.py
MetricFlow is not compatible with all DB engines supported by dbt Core yet. Currently, triggering a dbt Core sync in this scenario would raise an error. This PR gracefully handles this case and still processes legacy metrics.
Fixes https://github.com/preset-io/backend-sdk/issues/288.
> fix(dbt Core): Support syncing metrics without a MetricFlow dialect

- src/preset_cli/api/clients/dbt.py
- tests/api/clients/dbt_test.py
In the past, dbt had a unique base domain for all API requests:
``` python
REST_ENDPOINT = URL("https://cloud.getdbt.com/")
METADATA_GRAPHQL_ENDPOINT = URL("https://metadata.cloud.getdbt.com/graphql")
SEMANTIC_LAYER_GRAPHQL_ENDPOINT = URL(
"https://semantic-layer.cloud.getdbt.com/api/graphql",
)
```
They've changed their architecture and now customers have a dedicated URL -- this was already covered in the repo, but we were missing the paths.
> fix(dbt Cloud): Including GraphQL path for custom endpoints

- src/preset_cli/api/clients/dbt.py
- tests/api/clients/dbt_test.py
We were previously fetching legacy metrics with the `metrics(jobId: $jobId)` query, which was not working properly with new jobs as the `jobId` is an `Int!` for this query (and job IDs are exceeding the 32-bit limit).
This PR uses the `job(id: $jobId)` query which accepts/support a `BigInt!`.
> fix(dbt Cloud): Update dbt metadata GraphQL query

- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/lib_test.py
The CLI currently uses MetricFlow to retrieve the syntax for a metric. This current process has two issues:
* The `mf` command can take a few minutes for each metric (causing a full sync to take a long time)
* The `mf` command might return a SQL query with un-necessary `JOIN`s that is not compatible with dataset metrics in Superset.
To workaround this issue, this PR adds support for specifying the metric SQL syntax that should be used in Superset directly in `metric.meta.superset.expression`. In this case, since the metric won't be evaluated it's also required to specify the `metric.meta.superset.model` (so that the CLI knows which dataset to associate the metric):
``` yaml
metrics:
- name: test_distinct
description: test
type: simple  # Will be ignored in this case
label: Test …
```
> chore(dbt Core): Bypass metric evaluation if final SQL is provided

- .pre-commit-config.yaml
[types-pkg-resources](https://pypi.org/project/types-pkg-resources) have been yanked -- they recommend using `types-setuptools` instead.
> fix(pre-commit): Updating mirrors-mypy dependencies

- src/preset_cli/api/clients/dbt.py
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/datasets_test.py
- tests/cli/superset/sync/dbt/lib_test.py
- tests/cli/superset/sync/dbt/metrics_test.py
dbt introduced new restrictions to metric names with MetricFlow (for example, it's no longer possible to have `__` in metric names). As a consequence, in order to upgrade to a supported version customers have to update all their metric names according to new rules. The metric mapping with Preset happens based on the metric name, so a re-name in dbt would result in new metrics in Preset, leaving old metrics out of sync. 
This PR introduces a way to map a dbt metric with a Preset metric with diverging names, to minimize the impact of this change. 
This PR also improves the `meta` handling in general for metrics (so that Preset-specific fields can be controlled through dbt) and also improves the handling for the metric `label` (it wasn't being pulled from MetricFlow metrics).
> feat(dbt sync): Support metric key remapping

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
When syncing datasets with the `--preserve-metadata` or `--merge-metadata` flags, a request to sync the dataset columns is triggered. Currently, in case this request fails the command execution is aborted. 
This PR gracefully handles failures, adding the failed dataset to the list of `failed_datasets` (which can be listed at the end in case `--raise-failures` is used).
> fix(dbt): Keep syncing datasets if one failed to sync columns

- src/preset_cli/api/clients/dbt.py
- tests/api/clients/dbt_test.py
We support both legacy/OG metrics and also semantic layer metrics. To handle both cases, the dbt Cloud integration triggers two GraphQL calls:
* one to fetch OG metrics (via `get_og_metrics`).
* one to fetch SL metrics (via `get_sl_metrics`).
dbt recently released [versionless](https://docs.getdbt.com/docs/dbt-versions/versionless-cloud), so that you don't have to manage/upgrade environment versions. With `versionless` jobs, both OG and SL metrics are returned by the GraphQL call used in `get_og_metrics`.
This PR skips SL metrics in this first request, as they'll be properly handled in the second one.
> chore(dbt Cloud): Support versionless jobs

- .pre-commit-config.yaml
- src/preset_cli/cli/superset/export.py
- tests/cli/superset/export_test.py
- tests/cli/superset/main_test.py
PR adds an optional argument to the CLI export commands to force Unix EOLs for the exported files.  This is intended to address issues when exporting into Windows environments where we have multiple developers using different OS.
> Add option to force Unix EOL on YAML export via the CLI

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
By default, all import operations are executed using the Assets endpoint (`/api/v1/assets/import`), which overwrites all content in the target instance. While this is extremely useful when managing assets as code (to enforce the repo is always the source of truth) there are certain use-cases in which you might want to push assets without overwriting dependencies (updating a dataset without affecting the DB connection, push a chart update without updating datasets, etc) similar to the UI import flow.
This PR adds this capability to the `sync native` command. It's now possible to specify an ``--asset-type`` in the command (`dashboard` | `chart` | `dataset` | `database`) which defines the API endpoint used by the import (`/api/v1/{{asset_type}}/import`). As a consequence:
* When …
> feat: Support importing specific asset types

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
Currently, importing a dashboard with filter dividers will break as the import of the dataset filters expects a 'targets' field in the yaml config file. However, a filter divider, which has no target, can still be imported if the 'targets' field defaults to an empty `dict`.
> Adding ability to import dataset asset with no 'targets' field like filter divider

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
This PR adds a new feature for the dbt sync: the ability to specify default configs for metrics and columns. This allows you to have default values at the model level, and then if needed overwrite these for specific columns and metrics.
To re-cap, there are 3 dbt sync behaviors:
All metrics defined in dbt are synced to Superset (if the metric already exists in Superset, it gets entirely replaced by dbt's metadata). Column definitions from dbt are also synced to Superset.
In this flow, metric default configs would be applied to all metrics (unless the config is defined at the metric level), and column default configs would be applied to all columns (unless the config is defined at the column level) - even columns that are not defined in dbt.
All metrics defined in dbt are synced to …
> feat(dbt): Support defining default values for columns and metrics

- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/import_.py
- src/preset_cli/cli/superset/lib.py
- src/preset_cli/cli/superset/sync/native/command.py
- tests/api/clients/superset_test.py
- tests/cli/superset/import_test.py
- tests/cli/superset/lib_test.py
- tests/cli/superset/sync/native/command_test.py
https://github.com/preset-io/backend-sdk/pull/328 added the ability to complete an import if errors happen. This PR extends this logic to the ``import-ownership`` command:
* If a failure happens, it gets logged and the import continues.
* It also skips any asset that was failed to import with the ``import-assets`` command.
Some of the logic is redundant to both commands, so it got moved to a new ``lib.py`` file.
> feat(import ownership): Continue on error + skip import failures

- .pre-commit-config.yaml
- setup.cfg
- src/preset_cli/cli/superset/sync/dbt/command.py
- tests/cli/superset/sync/dbt/command_test.py
This PR removes the `--preserve-columns` flag, as it's been re-named to `--preserve-metadata` in https://github.com/preset-io/backend-sdk/pull/238.
> chore: Remove the --preserve-columns flag

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
This PR adds support for syncing calculated columns from the dbt model. These should be defined under `$model.meta.superset.calculated_columns` (list).
The behavior is:
**Default sync (`reload_columns` set to `True` and `merge_metadata` set to `False`)**
In this configuration, metrics from dbt are synced to Superset, and metrics that were only present in the dataset (and not in the model) are deleted. This is the same behavior for calculated columns:
* If there isn't any calculated columns defined in dbt, then existing calculated columns from the dataset are preserved. This is to avoid breaking changes (as currently calculated columns aren't deleted in this flow).
* If there's any calculated column defined in dbt, then these are synced and Superset-only calculated columns are removed. …
> feat(dbt sync): Sync calculated columns from dbt

- src/preset_cli/cli/superset/import_.py
- src/preset_cli/cli/superset/lib.py
- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/import_test.py
- tests/cli/superset/lib_test.py
- tests/cli/superset/sync/native/command_test.py
This PR implements the remaining feedback from https://github.com/preset-io/backend-sdk/pull/331 + enforces the progress is written to the log file continuously (as opposed to just at the end) so that if the command is aborted/cancelled progress is stored.
> chore: Write to log file after every step

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
This PR adds support for the `--asset-type` selector for individual imports. This allows users to trigger an import for a specific asset type (including dependencies) that get imported via the asset type endpoint.
It also fixes a logic gap that was introduced in https://github.com/preset-io/backend-sdk/pull/328 -- while it's correct that successful files added to the `progress.log` should be skipped, they should still be added to the `assets_config` dict as they might be dependencies to existing assets.
> feat: Support the --asset-type argument for individual imports

- src/preset_cli/cli/superset/sync/dbt/command.py
- tests/cli/superset/sync/dbt/command_test.py
Currently the dbt Cloud sync command expects that the DB connection in Preset is created based on the DB name in dataset (the actual database name). Keeping these matched is non intuitive, specially now that Superset supports multi-catalog (meaning that a single DB connection in Superset can interact with n catalogs).
This PR introduces the ability to specify a `--database-id=x` in the dbt Cloud command to perform the mapping.
> feat(dbt Cloud): Specify the DB ID in the command

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
Currently when importing a new DB connection the CLI prompts the user to enter its password. This PR adds the ability to specify the DB password as an argument to the CLI command, to skip the prompt (better for automations/integrations).
> feat(import assets): Pass DB passwords in the import command

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
Currently we're logging when importing a file, but we still iterate through other files (dependencies) that don't get imported, and an issue could occur during this step. This additional `debug` statement helps troubleshooting this issue.
> chore: Add debug logging for import resources individually

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
When running an import with the `--split` and `--continue-on-error` flags, the CLI imports each asset individually, dynamically identifying all dependencies to build a ZIP file to use.
We were currently handling any import failures (by adding it to the `progress.log` file and moving to the next item) but it's also possible that some issues happen while getting all dependencies from an asset. For example, if you delete a chart that's used in a dashboard and reflect this change in the `position`, the dashboard would have a `chart` element with `uuid: None`. 
This PR moves the logic to get all dependencies inside the `try/except` block, so that these failures don't interrupt the import (and are also added to the `progress.log` file).
> chore(sync native): Continue the import in case an error happens while getting dependencies

- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/import_.py
- tests/api/clients/superset_test.py
- tests/cli/superset/import_test.py
The `import-ownership` command would repeat API calls to get each asset by type and all users for every new asset ownership configuration being imported. 
This PR changes this flow to fetch the users only once, and the assets only once per type.
> chore: Reduce the amount of API calls executed by the import ownership

- src/preset_cli/api/clients/preset.py
- tests/api/clients/preset_test.py
- tests/api/clients/superset_test.py
In Preset, the Superset Users List view is disabled (since users are managed through Preset Manager). That said, in order to export users (with their local Superset IDs) we would parse the DOM of the Add DAR view. 
There was a change to this view so that the users are not loaded to the DOM anymore -- instead, there's a user search field. 
This PR updates the logic specifically for Preset Cloud to get the user information from the `/api/v1/chart/related/owners` field (which lists all members with proper pagination).
This is a temporary fix, as there's ongoing work to migrate the Superset Roles view to RESTful, and later do the same with Preset's DAR view.
> fix(Preset): Export users

- src/preset_cli/api/clients/preset.py
- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/import_.py
- tests/api/clients/superset_test.py
The `import-ownership` command needs to get all users from the Workspace (or Superset instance) and compare them with the YAML. It's possible the Superset instance has emails with uppercase characters (or the Preset Workspace). This PR normalizes all emails to lowercase before doing any comparison.
> fix(import ownership): Support emails with uppercase characters

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/cli/superset/sync/dbt/datasets_test.py
During the `sync_dataset()` process, we call `client.update_dataset()` twice (and we're currently including `override_columns=reload_columns` in both commands):
First to update the dataset metadata:
``` python
update = compute_dataset_metadata(
model,
certification,
disallow_edits,
final_dataset_metrics,
base_url,
final_dataset_columns,
)
client.update_dataset(
dataset["id"], override_columns=reload_columns, **update
)
```
Then to update its columns:
``` python
dbt_columns = model.get("columns")
if dbt_columns or calculated_columns:
current_dataset_columns = client.get_dataset(dataset["id"])["columns"]
dataset_columns = compute_columns_metadata(
dbt_columns,
current_dataset_columns,
reload_columns,
merge_metadata,
default_configs.get("columns", {}),
calculated_columns,
) …
```
> fix: Do not use reload_columns twice during dataset update

- src/preset_cli/cli/superset/export.py
- tests/cli/superset/export_test.py
The export command validates if the exported assets already exist in the target directory, raising if any asset already exists and the `overwrite` flag is not included. The current validation is solely based on the file name, which is not ideal as assets can be renamed in Superset, leading to duplicated files in the directory, and causing a race condition during import (the one imported last reflects in the UI).
This PR updates the logic to first check by file name, and then checks by `uuid`.
> feat: Local overwrite based on uuid
