- src/preset_cli/cli/main.py
- tests/cli/main_test.py
If the user has a single workspace don't prompt them for it.
> feat: don't prompt for WS if user has 1

- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
Closes https://github.com/preset-io/backend-sdk/issues/18.
> feat (dbt): redshift

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
Closes https://github.com/preset-io/backend-sdk/issues/46.
> fix: paginate when getting resources

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
> fix: initial page on `get_resources`

- README.rst
- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
Adds `--exclude` flag to dbt sync.
> feat: add exclude and docs for dbt selection

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
Closes https://github.com/preset-io/backend-sdk/issues/52
> feat: paginate exports

- README.rst
- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/export.py
- src/preset_cli/cli/superset/main.py
- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/api/clients/superset_test.py
- tests/cli/superset/export_test.py
- tests/cli/superset/main_test.py
Add new command to export users to a YAML file. Eg:
```bash
superset-cli -u admin -p admin http://localhost:8088/ export-users users.yml
```
> feat: export_users

- README.rst
- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/export.py
- src/preset_cli/cli/superset/main.py
- tests/api/clients/superset_test.py
- tests/cli/superset/export_test.py
- tests/cli/superset/main_test.py
Export RLS rules:
```bash
preset-cli superset export-rls [rls.yaml]
```
Will export RLS rules into `rls.yaml`.
> feat: export RLS

- src/preset_cli/api/clients/superset.py
- src/preset_cli/cli/superset/import_.py
- src/preset_cli/cli/superset/main.py
- tests/api/clients/superset_test.py
- tests/cli/superset/export_test.py
- tests/cli/superset/import_test.py
- tests/cli/superset/main_test.py
Add a command for importing RLS, complementing https://github.com/preset-io/backend-sdk/pull/57.
> feat: import RLS

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
Fix a few bugs:
- When assigning ownership, ignore resources that don't exist in the server.
- When importing RLS, check that the role has no permissions (otherwise it will fail silently).
> fix: import/export

- src/preset_cli/api/clients/superset.py
- tests/api/clients/superset_test.py
Add users to roles when importing them.
> feat: import roles with users

- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
> fix: BigQuery DB creation

- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
> fix: use Redshift driver

- src/preset_cli/cli/superset/sync/dbt/datasets.py
- tests/api/clients/superset_test.py
- tests/cli/superset/sync/dbt/datasets_test.py
> fix: bigquery db detection

- src/preset_cli/api/clients/superset.py
This is needed for dashboard export.
> feat: reduce `MAX_IDS_IN_EXPORT`

- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
Support authenticating to Snowflake using private keys.
Users should have `private_key_path` and `private_key_passphrase` in the dbt profile configuration.
> feat: snowflake pk

- src/preset_cli/cli/superset/sync/native/command.py
Remove duplicate logic when rendering YAML.
> chore: improve YAML rendering

- .github/workflows/python-package.yml
- .pre-commit-config.yaml
- .pylintrc
- dev-requirements.txt
- setup.cfg
- src/preset_cli/auth/lib.py
- src/preset_cli/auth/main.py
- src/preset_cli/auth/password.py
- tests/api/clients/superset_test.py
Fix the `flake8` pre-commit test, and run all of them on CI.
> chore: run lint tests on CI

- README.rst
- src/preset_cli/cli/superset/sync/dbt/datasets.py
* Fixed two typos
* Removed the `--overwrite` flag from the dbt sync since it's not required (that's controlled by the `--import-db`).
> fix:Minor changes

- README.rst
Adding documentation to export specific resources.
> Including instructions on how to export specific resources to the README file 

- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/metrics_test.py
Add some debugging logic for a prospect.
> chore(dbt): add debug info for derived metrics

- CHANGELOG.rst
Updating `CHANGELOG` to release version 0.2.7.
> chore: Release v0.2.7

- CHANGELOG.rst
Updating `CHANGELOG` to release version 0.2.8.
> chore: Release v0.2.8

- CHANGELOG.rst
Update changelog in preparation for release.
> chore: release 0.2.9

- src/preset_cli/cli/superset/sync/dbt/command.py
- src/preset_cli/cli/superset/sync/dbt/metrics.py
- tests/cli/superset/sync/dbt/command_test.py
- tests/cli/superset/sync/dbt/metrics_test.py
A small refactor making the `get_model_from_sql` function more generic.
> chore(dbt): refactor get_model_from_sql

- CHANGELOG.rst
Update Changelog for new release.
> chore: new release

- CHANGELOG.rst
Updaring `CHANGELOG` for new release.
> chore: 0.2.12 release

- CHANGELOG.rst
> chore: release 0.2.16

- src/preset_cli/cli/superset/sync/dbt/datasets.py
> chore: simplify code

- src/preset_cli/api/clients/preset.py
- tests/api/clients/preset_test.py
- tests/api/clients/superset_test.py
Manager APIs now support pagination. This PR implements pagination to Manager API calls.
> chore: Paginate Manager API calls

- CHANGELOG.rst
> chore: Release 0.2.21

- src/preset_cli/cli/superset/sync/native/command.py
- tests/cli/superset/sync/native/command_test.py
The CLI was currently only verifying connectivity/adding the provided password to the config for new connections. This PR fixes this flow, so that whenever a password is provided (either in the connection string, through the command, etc) connectivity is validated and (if needed) the password is properly added to the config.
> fix(sync native): Always update DB password if provided

- src/preset_cli/cli/superset/sync/dbt/lib.py
- tests/cli/superset/sync/dbt/lib_test.py
This PR adds support for filtering dbt models using a nested config property (such as `config.meta.$key`).
> feat(dbt sync): Support using nested properties under `config` to filter models
